"""clubs table

Revision ID: 66318fcbbf3e
Revises: 3ab774900d8e
Create Date: 2023-03-16 12:19:45.599091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66318fcbbf3e'
down_revision = '3ab774900d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_name'), ['name'], unique=True)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index('ix_clubs_name')

    op.drop_table('clubs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index('ix_clubs_name', ['name'], unique=False)

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_name'))

    op.drop_table('club')
    # ### end Alembic commands ###
