"""remove profile pic

Revision ID: 67cb5c0d77dd
Revises: 0fc7aee7a9a9
Create Date: 2023-05-16 18:16:48.276131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cb5c0d77dd'
down_revision = '0fc7aee7a9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
