"""update Club table

Revision ID: d2533444244b
Revises: ea9640fb085e
Create Date: 2023-04-06 14:50:33.025376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2533444244b'
down_revision = 'ea9640fb085e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_index('ix_club_user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.create_index('ix_club_user_name', ['user_name'], unique=False)

    # ### end Alembic commands ###
