"""empty message

Revision ID: ea9640fb085e
Revises: 9f9471fa966a
Create Date: 2023-04-05 14:43:55.926690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9640fb085e'
down_revision = '9f9471fa966a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_club_user_name'), ['user_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_user_name'))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
